import React, { useEffect, useRef, useState } from 'react'
import { ecKdRefresh } from '../api.js'
import EcomFlowLedger, { AccountTable } from './EcomFlowLedger.jsx'
import { requestJson, wb, query, post, money, count, percent, useResource } from './ecomWorkbenchApi.js'
import './ecomWorkbench.css'
import overviewIcon from '../assets/ecom-nav/chart-bar.svg'
import prepareIcon from '../assets/ecom-nav/notes.svg'
import incomeIcon from '../assets/ecom-nav/clipboard-check.svg'
import cashIcon from '../assets/ecom-nav/coin-yuan.svg'
import flowsIcon from '../assets/ecom-nav/receipt.svg'

// Shops are resolved from source-backed base data, never a hardcoded display name.
const NAV=[
  ['overview','总览','经营与账户概览',overviewIcon],
  ['prepare','数据准备','按店铺准备资料',prepareIcon],
  ['income','收入确认','发货与应收核对',incomeIcon],
  ['cash','收款核销','支付宝与聚合账户',cashIcon],
  ['flows','账户流水','全字段合并查找',flowsIcon],
]
const BUSINESS={ '':'全部订单',normal:'正常销售',ufirst:'U先试用装',mixed:'混合订单',review:'待确认分类',unknown:'待分类' }
export const Notice=({children}) => children ? <div className="ew-notice" role="status">{children}</div> : null
const Panel=({title,children,extra}) => <section className="ew-panel"><header><h2>{title}</h2>{extra}</header>{children}</section>
function Metric({label,value,sub,onClick}) {const Tag=onClick?'button':'div';return <Tag className="ew-metric" onClick={onClick}><span>{label}</span><strong>{value}</strong><small>{sub}</small></Tag>}

export default function EcomWorkbench({user,onNav,initialScreen='overview'}) {
  const [screen,setScreen]=useState(initialScreen),[period,setPeriod]=useState('2026-08'),[shop,setShop]=useState(''),[business,setBusiness]=useState(''),[flag,setFlag]=useState(''),[revision,setRevision]=useState(0),[drawer,setDrawer]=useState(null),[message,setMessage]=useState(''),[flowFilter,setFlowFilter]=useState({})
  const result=useResource(`/api/ec/workbench/overview?${query({period,business})}`,revision)
  const overview=result.data
  const canEdit=user?.role==='admin'||user?.perms?.ec_settle_upload
  useEffect(() => {if (!shop && overview?.shops?.length) setShop(overview.shops.find(s=>s.platform==='天猫' && s.available)?.id || overview.shops[0].id)},[overview,shop])
  useEffect(() => {setScreen(initialScreen)},[initialScreen])
  const changePeriod=e=>{setPeriod(e.target.value);setDrawer(null);setFlag('')}
  const drill=(id,filter='',next='income')=>{setShop(id);setFlag(filter);setScreen(next)}
  const openLedger=(filter={})=>{setFlowFilter(filter);setDrawer(null);setScreen('flows')}
  return <div className="ew-workbench">
    <header className="ew-header"><div><h1>电商对账工作台</h1><p>平台事实 → 发货确认 → 应收核对 → 账户收款</p></div><div className="ew-header-tools"><span className="ew-readonly">金蝶只读</span>{screen!=='flows' && <label>结算期间<input aria-label="结算期间" type="month" value={period} onChange={changePeriod}/></label>}<button onClick={()=>setRevision(v=>v+1)}>刷新数据</button><button className="ew-link ew-basic" onClick={()=>onNav?.('ecombase')}>基础资料</button></div></header>
    <nav className="ew-nav ew-stage-nav" aria-label="电商工作流">{NAV.map(([key,label,description,icon])=><button key={key} aria-label={label} aria-current={screen===key?'page':undefined} className={screen===key?'active':''} onClick={()=>{setScreen(key);setFlag('')}}><span className="ew-stage-symbol" aria-hidden="true"><span className="ew-stage-icon" style={{maskImage:`url(${JSON.stringify(icon)})`,WebkitMaskImage:`url(${JSON.stringify(icon)})`}}/></span><span className="ew-stage-copy"><strong>{label}</strong><small>{description}</small></span></button>)}</nav>
    {screen!=='flows' && <div className="ew-filter"><span>业务范围</span>{Object.entries(BUSINESS).slice(0,4).map(([key,label])=><button key={key} className={business===key?'active':''} onClick={()=>setBusiness(key)}>{label}</button>)}<span className="ew-muted">覆盖 {overview?.coverage?.available ?? '—'} / {overview?.coverage?.total ?? '—'} 家店铺 · 缺数据不计作零</span></div>}
    <Notice>{message||result.error}</Notice>
    {screen==='flows' ? <EcomFlowLedger refreshToken={revision} onChanged={()=>setRevision(v=>v+1)} user={user} period={flowFilter.q?'':period} initialQuery={flowFilter.q||''} initialAccountId={flowFilter.account_id||''}/> : screen==='overview' ? <Overview data={overview} loading={result.loading} revision={revision} drill={drill} openCash={id=>openLedger({account_id:typeof id==='string'?id:''})}/> : <div className="ew-layout"><aside className="ew-shops"><h2>店铺数据准备</h2>{overview?.shops?.map(s=><button key={s.id} className={shop===s.id?'active':''} onClick={()=>{setShop(s.id);setFlag('');setDrawer(null)}}><span><i className={s.readiness}/>{s.name}</span><small>齐套 {s.ready}/{s.required} · 文件 {s.files}</small></button>)}</aside><main className="ew-main">
      {screen==='prepare' && shop && <Preparation key={shop+period} period={period} shop={shop} revision={revision} canEdit={canEdit} refresh={()=>setRevision(v=>v+1)} notify={setMessage}/>}
      {(screen==='income'||screen==='cash') && shop && <OrderWorkspace key={shop+period+screen} user={user} period={period} shop={shop} mode={screen} business={business} flag={flag} setFlag={setFlag} revision={revision} openOrder={(no,tab='flow')=>setDrawer({no,tab})}/>}
      {screen==='prepare' && <Panel title="资金流水准备"><EcomFlowLedger managementOnly user={user} refreshToken={revision} onChanged={()=>setRevision(v=>v+1)}/></Panel>}
    </main></div>}
    <p className="ew-footnote">GSV = 支付成功金额 − 已成功退款，未扣平台费用。订单按创建月归属；收款以支付宝 / 聚合账户入账为止，不代表已提现到公司银行。今晚金蝶仅查询，禁止新增、下推、提交或审核。</p>
    {drawer && <OrderDrawer period={period} shop={shop} orderNo={drawer.no} initialTab={drawer.tab} onClose={()=>setDrawer(null)} onOpenLedger={()=>openLedger({q:drawer.no})}/>}
  </div>
}

function Overview({data,loading,revision,drill,openCash}) {
  const accounts=useResource('/api/ec/flows/accounts',revision),m=data?.totals
  return <div className="ew-overview"><div className="ew-metrics"><Metric label="订单数" value={count(m?.orders)} sub="按创建月份归属"/><Metric label="GMV · 支付成功金额" value={`¥ ${money(m?.gmv)}`} sub="仅支付成功订单"/><Metric label="GSV · 净成交金额" value={`¥ ${money(m?.gsv)}`} sub="扣退款 · 未扣平台费用"/><Metric label="平台费用" value={`¥ ${money(m?.fees)}`} sub="按已匹配订单流水归集"/></div>
    <div className="ew-attention"><div>仅退款<strong>¥ {money(m?.refund_only)}</strong><small>金额占 GMV {percent(m?.refund_only_rate)}</small></div><div>退货退款<strong>¥ {money(m?.return_refund)}</strong><small>金额占 GMV {percent(m?.return_refund_rate)}</small></div><div>未发货<strong>{count(m?.unshipped_count)} 笔 / ¥ {money(m?.unshipped_amount)}</strong><small>已支付、尚未发货的有效订单</small></div><div>待人工介入<strong>{count(m?.manual)} 笔</strong><small>按订单去重，不重复累加问题数</small></div></div>
    {m?.unknown_refund>0 && <Notice>尚有 ¥ {money(m.unknown_refund)} 退款未取得明确售后类型，暂不归入“仅退款”或“退货退款”。请在数据准备补充售后明细。</Notice>}
    <Panel title="店铺经营与核对概览" extra={<span className="ew-muted">总览 → 店铺 → 订单证据</span>}><div className="ew-scroll"><table><thead><tr><th>店铺 / 齐套状态</th><th>订单数</th><th>GMV</th><th>GSV</th><th>仅退款 / 比例</th><th>退货退款 / 比例</th><th>费用</th><th>未发货 / 金额</th><th>待人工介入</th></tr></thead><tbody>{data?.shops?.map(s=><tr key={s.id}><td><button className="ew-link" onClick={()=>drill(s.id)}><i className={'ew-dot '+s.readiness}/>{s.name}</button><small>{s.ready}/{s.required} 类 · {s.files} 个文件</small></td><td>{count(s.metrics?.orders)}</td><td>{money(s.metrics?.gmv)}</td><td>{money(s.metrics?.gsv)}</td><td><button className="ew-link" onClick={()=>drill(s.id,'refund_only')}>{money(s.metrics?.refund_only)}</button><small>{percent(s.metrics?.refund_only_rate)}</small></td><td><button className="ew-link" onClick={()=>drill(s.id,'return_refund')}>{money(s.metrics?.return_refund)}</button><small>{percent(s.metrics?.return_refund_rate)}</small></td><td><button className="ew-link" onClick={()=>drill(s.id,'fees','cash')}>{money(s.metrics?.fees)}</button></td><td><button className="ew-link" onClick={()=>drill(s.id,'unshipped')}>{count(s.metrics?.unshipped_count)} 笔</button><small>{money(s.metrics?.unshipped_amount)}</small></td><td><button className="ew-link" onClick={()=>drill(s.id,'manual')}>{count(s.metrics?.manual)}</button></td></tr>)}{(!data || loading)&&<tr><td colSpan="9" className="ew-empty">{loading?'正在汇总各店铺数据…':'暂无数据'}</td></tr>}</tbody><tfoot><tr><td>已接入店铺合计</td><td>{count(m?.orders)}</td><td>{money(m?.gmv)}</td><td>{money(m?.gsv)}</td><td>{money(m?.refund_only)}</td><td>{money(m?.return_refund)}</td><td>{money(m?.fees)}</td><td>{count(m?.unshipped_count)} 笔</td><td>{count(m?.manual)}</td></tr></tfoot></table></div></Panel>
    <Panel title="资金账户余额" extra={<button className="ew-link" onClick={()=>openCash('')}>查找账户流水</button>}><Notice>{accounts.error}</Notice><AccountTable data={accounts.data} onSelect={openCash}/><p className="ew-muted ew-padding">一个账户一行；共享账户不按店铺重复汇总。余额以原文件实际字段为准，不使用净收支推算。</p></Panel>
  </div>
}

function Preparation({period,shop,revision,canEdit,refresh,notify}) {
  const result=useResource(`/api/ec/workbench/sources?${query({period,shop})}`,revision),data=result.data
  const [kind,setKind]=useState('order'),[busy,setBusy]=useState(false),[inbox,setInbox]=useState(null),input=useRef(null)
  useEffect(()=>{if (!data?.voucher_sync?.running && !data?.kingdee?.refreshing) return;const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[data?.voucher_sync?.running,data?.kingdee?.refreshing])
  const act=async fn=>{setBusy(true);try{await fn();refresh()}catch(e){notify(e.message)}finally{setBusy(false)}}
  const upload=e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;act(async()=>{const body=new FormData();body.append('period',period);body.append('shop',shop);body.append('kind',kind);files.forEach(f=>body.append('files',f));const r=await wb('upload',{method:'POST',body});notify(r.duplicate?'同一文件已导入，保留原快照':`导入成功：${count(r.rows)} 行。`)})}
  return <><Notice>{result.error}</Notice><Panel title="月结资料清单" extra={<span className="ew-muted">按店铺、按数据类别准备</span>}><div className="ew-tools"><select aria-label="导入数据类别" value={kind} onChange={e=>setKind(e.target.value)}>{data?.sources?.filter(s=>!['alipay','fund'].includes(s.kind)).map(s=><option key={s.kind} value={s.kind}>{s.label}</option>)}</select><input ref={input} hidden type="file" multiple={kind==='alipay'} accept=".xlsx,.xls,.zip" onChange={upload}/><button className="ew-primary" disabled={!canEdit||busy} onClick={()=>input.current?.click()}>{busy?'正在处理…':'选择文件导入'}</button><button onClick={()=>act(async()=>setInbox(await wb(`inbox?${query({period,shop})}`)))}>查看公盘取件状态</button></div><p className="ew-muted ew-padding">平台订单、商品、出库及售后文件在此导入；账户登记与支付宝 / 聚合账户流水导入见下方，查询请前往「账户流水」。</p><div className="ew-scroll"><table><thead><tr><th>数据类别</th><th>状态</th><th>有效行数</th><th>来源文件</th><th>导入时间</th></tr></thead><tbody>{data?.sources?.map(s=><tr key={s.kind}><td>{s.label}</td><td><span className={`ew-status ${s.available?'warning':'missing'}`}>{s.available?'已导入'+(s.legacy?' · 历史快照':''):'待准备'}</span></td><td>{count(s.rows)}</td><td>{s.files?.join('、')|| (s.legacy?'原版本核算快照':'—')}<small>{s.warnings?.join('；')}</small></td><td>{s.imported_at||'—'}</td></tr>)}</tbody></table></div>{inbox&&<Notice>{inbox.message}{inbox.files?.length>0&&<ul>{inbox.files.map(f=><li key={f.name}>{f.name}</li>)}</ul>}</Notice>}</Panel>
    <Panel title="收入确认口径与金蝶只读取数"><div className="ew-tools"><label>收入确认<select value={data?.rule?.recognition||'shipment'} disabled={!canEdit||busy} onChange={e=>act(()=>wb('rules',post({period,shop,recognition:e.target.value})))}><option value="shipment">发货确认收入</option><option value="confirmed">确认收货后确认收入</option></select></label><button disabled={!canEdit||busy} onClick={()=>act(async()=>{await ecKdRefresh(period);notify('已发起金蝶应收只读同步，请稍后刷新状态。')})}>读取金蝶应收</button><button disabled={!canEdit||busy||data?.voucher_sync?.running} onClick={()=>act(async()=>{await wb('kingdee-docs/refresh',post({period,shop}));notify('已发起历史凭证只读查询。')})}>{data?.voucher_sync?.running?'凭证查询中…':'读取历史凭证'}</button></div><p className="ew-muted ew-padding">U先单独汇总，不因缺少旺店通出库或应收单报警。收款单来源链未证明前不标记“已下推”。所有取数仅查询金蝶。</p><Notice>{data?.voucher_sync?.error}</Notice></Panel></>
}

function OrderWorkspace({user,period,shop,mode,business,flag,setFlag,revision,openOrder}) {
  const [q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[cashTab,setCashTab]=useState('orders')
  useEffect(()=>{setPage(1)},[business,flag,search])
  const result=useResource(cashTab==='orders'?`/api/ec/workbench/orders?${query({period,shop,business,flag,q:search,page})}`:null,revision),data=result.data
  return <><h2 className="ew-section-title">{mode==='income'?'收入确认':'收款核销'}</h2>{mode==='cash'&&<div className="ew-subnav">{[['orders','订单收款'],['preview','凭证预览'],['history','历史核销记录']].map(([key,label])=><button key={key} className={cashTab===key?'active':''} onClick={()=>setCashTab(key)}>{label}</button>)}</div>}
    {cashTab==='flows'?<EcomFlowLedger user={user} period={period}/>:cashTab==='preview'?<VoucherPreview period={period} shop={shop} revision={revision}/>:cashTab==='history'?<History period={period} shop={shop}/>:<><Notice>{result.error}</Notice><form className="ew-tools" onSubmit={e=>{e.preventDefault();setSearch(q);setPage(1)}}><input aria-label="查找订单" value={q} onChange={e=>setQ(e.target.value)} placeholder="平台订单号、商品或 SKU"/><select aria-label="订单检查筛选" value={flag} onChange={e=>setFlag(e.target.value)}><option value="">全部订单</option><option value="manual">待人工介入</option><option value="unshipped">未发货</option><option value="ar_missing">已发货未匹配应收</option><option value="refund_only">仅退款</option><option value="return_refund">退货退款</option><option value="unknown_refund">退款类型待分类</option><option value="fees">有平台费用</option></select><button className="ew-primary">查找</button><span className="ew-muted">{count(data?.total)} 笔 · 日期在订单流转抽屉查看</span></form>
    <div className="ew-scroll ew-panel"><table className="ew-order-table"><thead><tr><th>平台订单 / 业务类型</th><th>订单金额</th><th>实付金额</th><th>退款金额</th>{mode==='income'?<><th>发货 / 应收</th><th>应收金额</th><th>核对提示</th></>:<><th>费用金额</th><th>账户净收</th><th>资金去向 / 核对提示</th></>}</tr></thead><tbody>{data?.rows?.map(r=><tr key={r.order_no}><td><button className="ew-link ew-order-id" onClick={()=>openOrder(r.order_no)}>{r.order_no}</button><small>{r.business_label} · {r.status}</small></td><td>{money(r.order_amount)}</td><td>{money(r.paid)}</td><td>{money(r.refund)}</td>{mode==='income'?<><td>{r.business_type==='ufirst'?'U先 · 总账汇总':r.should_ar?'已达到确认条件':'待确认条件'}<small>{r.ar_documents?.length?`匹配 ${r.ar_documents.length} 张应收单`:'未匹配应收单'}</small></td><td>{money(r.ar_amount)}<small>{r.ar_diff!=null?`差额 ${money(r.ar_diff)}`:'金额核对待补依据'}</small></td><td className="ew-issue">{r.issues?.join('；')||'已取得现有核对证据'}<button className="ew-link" onClick={()=>openOrder(r.order_no)}>查看证据</button></td></>:<><td><button className="ew-link" onClick={()=>openOrder(r.order_no,'cash')}>{money(r.fees)}</button></td><td>{money(r.net_receipt)}</td><td>{r.destination}<small className="ew-issue">{r.issues?.join('；')}</small></td></>}</tr>)}{(result.loading||!data?.rows?.length)&&<tr><td colSpan="7" className="ew-empty">{result.loading?'正在读取订单…':'当前筛选下没有订单'}</td></tr>}</tbody></table></div><div className="ew-pagination"><span>每页 30 笔</span><button disabled={page<=1||result.loading} onClick={()=>setPage(p=>p-1)}>上一页</button>{page} / {data?.pages||1}<button disabled={page>=(data?.pages||1)||result.loading} onClick={()=>setPage(p=>p+1)}>下一页</button></div></>}
  </>
}

function VoucherPreview({period,shop,revision}) {
  const result=useResource(`/api/ec/workbench/preview?${query({period,shop})}`,revision),data=result.data
  const [onlyU,setOnlyU]=useState(true)
  return <Panel title="金蝶凭证只读预览"><Notice>{result.error||data?.notice}</Notice><div className="ew-tools"><label><input type="checkbox" checked={onlyU} onChange={e=>setOnlyU(e.target.checked)}/> 只看 U先相关凭证</label><button disabled title="今晚金蝶只读">下推收款单 / 入账（未开放）</button></div>{data?.existing_vouchers?.filter(v=>!onlyU||v.ufirst).map(v=><details className="ew-voucher" key={v.bill} open><summary>{v.number} · {v.date?.slice(0,10)} · 状态 {v.status} · 单据编号 {v.bill}</summary><p className="ew-muted">摘要提及 {v.receipt_references?.join('、')||'无收款单号'}；仅为参考，尚未证明订单与收款单来源关系。</p><div className="ew-scroll"><table><thead><tr><th>摘要</th><th>科目</th><th>借方</th><th>贷方</th></tr></thead><tbody>{v.lines?.map((l,i)=><tr key={i}><td>{l.memo}</td><td>{l.account} {l.account_name}</td><td>{money(l.debit)}</td><td>{money(l.credit)}</td></tr>)}</tbody></table></div></details>)}{!data?.existing_vouchers?.length&&<p className="ew-empty">尚未读取参考凭证。请到数据准备读取历史凭证。</p>}<div className="ew-padding"><strong>新凭证预览前待确认</strong><ul>{data?.draft?.checks?.map(c=><li key={c}>{c}</li>)}</ul></div></Panel>
}
function History({period,shop}) {
  const result=useResource(`/api/ec/workbench/history?${query({period,shop})}`)
  const buckets={ok:'已匹配',ufirst:'U先汇总',crossed:'串单复核',carry:'跨期调节',real:'真实差异'}
  return <Panel title="历史订单核销记录"><Notice>{result.error}</Notice><p className="ew-muted ew-padding">这里保留原订单核销分桶，与账户流水业务分桶是两套不同的检查。</p><div className="ew-scroll"><table><thead><tr><th>批次</th><th>状态 / 时间</th><th>原核销结果</th></tr></thead><tbody>{result.data?.rows?.map(r=><tr key={r.id}><td>#{r.id}</td><td>{r.status}<small>{r.ts}</small></td><td>{Object.entries(r.stats?.buckets||{}).map(([key,v])=><span className="ew-history-bucket" key={key}>{buckets[key]||key} {count(v.cnt)} 笔</span>)}</td></tr>)}{!result.data?.rows?.length&&<tr><td colSpan="3" className="ew-empty">本店本期暂无历史核销批次</td></tr>}</tbody></table></div></Panel>
}

function OrderDrawer({period,shop,orderNo,initialTab,onClose,onOpenLedger}) {
  const result=useResource(`/api/ec/workbench/order?${query({period,shop,order_no:orderNo})}`),r=result.data?.order
  const [tab,setTab]=useState(initialTab),ref=useRef(null)
  useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll('button, input, select');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus()}},[])
  const events=r?[['平台订单创建',r.created_at,orderNo],['支付成功',r.paid_at,`实付 ¥ ${money(r.paid)}`],...(r.shipments||[]).map(s=>['旺店通发货',s.date,`${s.shipment_no} · ${s.status}`]),...(r.ar_documents||[]).map(a=>['金蝶应收',a.date,`${a.bill_no} · ¥ ${money(a.amount)}`]),...(r.events||[]).map(e=>[e.aggregate_copy?'聚合渠道映射（不重复计款）':e.channel==='alipay'?'支付宝入账':'聚合账户入账',e.date,`${e.label} · 收 ${money(e.income)} / 支 ${money(e.expense)}`])].filter(e=>e[1]).sort((a,b)=>a[1].localeCompare(b[1])):[]
  return <div className="ew-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="ew-drawer" role="dialog" aria-modal="true" aria-labelledby="order-drawer-title" tabIndex="-1" ref={ref}><header><div><span className="ew-muted">订单证据与流转</span><h2 id="order-drawer-title">{orderNo}</h2></div><button onClick={onClose}>关闭</button></header><Notice>{result.error}</Notice>{!r?<p>正在读取订单证据…</p>:<><div className="ew-drawer-metrics">{[['订单金额',r.order_amount],['实付金额',r.paid],['退款金额',r.refund],['费用金额',r.fees]].map(([l,v])=><div key={l}><small>{l}</small><strong>¥ {money(v)}</strong></div>)}</div><p>{r.business_label} · {r.status}</p><Notice>{r.issues?.join('；')}</Notice><div className="ew-subnav">{[['flow','订单流转'],['items','物料与单据'],['cash','费用与收款']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>{tab==='flow'?<><ol className="ew-timeline">{events.map(([title,date,detail],i)=><li key={i}><span>{date}</span><strong>{title}</strong><p>{detail}</p></li>)}</ol><Notice>只展示已有来源的事件。没有收款单来源链，不代表没有收款单；物流单号不等于已获取物流轨迹。</Notice></>:tab==='items'?<><h3>平台商品与子订单</h3><div className="ew-scroll"><table><thead><tr><th>子订单号</th><th>商品 / SKU</th><th>数量</th><th>实付</th></tr></thead><tbody>{r.items?.map((i,n)=><tr key={n}><td>{i.suborder_no}</td><td>{i.name}<small>{i.sku}</small></td><td>{i.quantity}</td><td>{money(i.paid)}</td></tr>)}</tbody></table></div><h3>旺店通出库与物流</h3>{r.shipments?.map((s,i)=><div className="ew-evidence" key={i}><strong>{s.shipment_no}</strong> · {s.status}<p>旺店通订单 {s.internal_order||'未提供'} · 原始订单 {s.original_order||r.order_no}</p><p>{s.name||s.sku} · {s.spec} · 数量 {s.quantity}</p><small>{s.logistics_company||'未提供物流公司'} · 快递单号 {s.logistics_no||'未提供'} · 发货 {s.date||'未提供'}</small></div>)}<h3>金蝶应收单</h3>{r.ar_documents?.map(a=><div className="ew-evidence" key={a.bill_no}>{a.bill_no} · {a.date} · ¥ {money(a.amount)}{a.has_red?' · 含红字':''}</div>)}{!r.ar_documents?.length&&<p className="ew-muted">{r.business_type==='ufirst'?'U先走总账汇总，不要求逐单应收。':'当前范围内未匹配应收单。'}</p>}</>:<><h3>平台费用逐笔构成</h3><div className="ew-scroll"><table><thead><tr><th>费用名称 / 费目码</th><th>账户</th><th>入账时间</th><th>支出</th><th>返还</th></tr></thead><tbody>{r.fee_events?.map((f,i)=><tr key={i}><td>{f.label}<small>{f.code}</small></td><td>{f.channel==='alipay'?'支付宝':'聚合账户'}</td><td>{f.date}</td><td>{money(f.expense)}</td><td>{money(f.income)}</td></tr>)}{!r.fee_events?.length&&<tr><td colSpan="5">当前已导入证据中没有匹配的费用流水，不代表全账户没有扣款。</td></tr>}</tbody></table></div><p>资金去向：{r.destination} · 账户净收 ¥ {money(r.net_receipt)}</p><Notice>{result.data.receipt_relation}</Notice><button onClick={onOpenLedger}>在账户流水页查这笔订单</button></> }</>}</section></div>
}
